version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - fichaTecnica

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8040:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - fichaTecnica

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "8042:3306"
        networks:
            - fichaTecnica

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:

            - app
        networks:
            - fichaTecnica

    # redis
    redis:
        image: redis:latest
        networks:
            - fichaTecnica
    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        ports:
            - "8041:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - fichaTecnica

networks:
    fichaTecnica:
        driver: bridge
